
import "./globals.css";
import Header from "components/modules/Header";
import Footer from "components/modules/Footer";



export const metadata = {
  title: "Create Torino App",
  description: "Generated by Parisa Abbasi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
